WIP : PluginFormcreatorForm::showForm() Use twig
pluginsGLPI/formcreator pull request #2519
Opened 2021-12-27 09:32 UTC by btry

use Twig in  PluginFormcreatorForm::showForm() 

Maybe merge this PR with all others twig conversions.

2021-12-27 09:33 UTC, btry commented on front/form.form.php
> +   Html::back();
extra : better rediretion

2022-01-03 12:43 UTC, btry commented on ajax/question_add.php
> -$question->getFromDB($question->getID()); // To remove if GLPI #9210 merged
the mentionned PR is merged

2022-01-03 12:43 UTC, btry commented on ajax/question_delete.php
> +    echo __('Question not found', 'formcreator');
if deletion fails, no error displayed, fixing it

2022-01-03 12:44 UTC, btry commented on css/styles.scss
> +
fix ribbon position when showForm() is used in a modal

2022-01-03 12:44 UTC, btry commented on css/styles.scss
> -   > ol {
less strict CSS to match the expected elements under GLPI 10

2022-01-03 12:45 UTC, btry commented on front/form.form.php
> +   Html::back();
obey $_SESSION['glpibackcreated'] preference

2022-01-03 12:46 UTC, btry commented on inc/common.class.php
> +      $list = $list ?? require_once(GLPI_PLUGIN_DOC_DIR . '/formcreator/' . self::getPictoFilename());
avoid failure if the require statement is ran twice

2022-01-03 12:46 UTC, btry commented on inc/common.class.php
> -   public static function getPictoFilename(string $version) : string {
obsolete argument removed

2022-01-03 12:47 UTC, btry commented on inc/condition.class.php
> +   public static function getConditionsFromItem(CommonDBTM $item) : array {
make method callable from a template

2022-01-03 12:47 UTC, btry commented on inc/condition.class.php
> +   public static function countForItem(PluginFormcreatorConditionnableInterface $item): int {
make countElementsInTable callable from a template

2022-01-03 12:48 UTC, btry commented on inc/condition.class.php
> +   public static function getQuestionsExclusion(PluginFormcreatorConditionnableInterface $item) {
isolate in dedicated method the code to exclude questions from a questions dropdown

2022-01-03 12:50 UTC, btry commented on inc/field/actorfield.class.php
> +               $knownUsers[$user->getID()] = $user->getFriendlyName();
remove backward compatibility with GLPI 9.5

2022-01-03 12:51 UTC, btry commented on inc/fieldinterface.class.php
> +   public function getQuestion();
fix an IDE warning

2022-01-04 14:41 UTC, AdrienClairembault requested changes

2022-01-04 14:43 UTC, AdrienClairembault commented
If I remember correctly; this option was set to 'Yes' by default in the previous version:

![image](https://user-images.githubusercontent.com/42734840/148075911-109105a1-08bc-42c2-ba7c-dcd7ddc5df91.png)

-> This option was requested as an edge case, most people will want it set to 'Yes' for all their forms.

2022-01-04 14:52 UTC, AdrienClairembault commented
Visual issues when creating a section:

![image](https://user-images.githubusercontent.com/42734840/148077347-50d784f6-4802-42b4-b66a-f05abc29d906.png)

2022-01-04 14:53 UTC, AdrienClairembault commented
After adding my section I can't add any question, the tab has an error: 
![image](https://user-images.githubusercontent.com/42734840/148077536-b1395de1-5e7c-465b-82b9-542f4f20b21d.png)

2022-01-04 14:54 UTC, btry commented on ajax/question_delete.php
> +    echo __('Question not found', 'formcreator');
The error mesage is processed by js/scripts.js. Your sgestion is possible, but also requires an update in the JS  code. This PR is complicated enough, then we may do this in a separate enhancement PR.

2022-01-04 15:00 UTC, AdrienClairembault commented
Adding an actor to a target doesn't seem to work:

![image](https://user-images.githubusercontent.com/42734840/148078396-e4af3ed3-2cbc-4b68-8362-addf222a74f3.png)

After save:

![image](https://user-images.githubusercontent.com/42734840/148078442-6251a657-95b1-4a1c-a3db-a90ebeb7d49e.png)

2022-01-04 15:01 UTC, AdrienClairembault commented
I'm unable to edit the target conditions:

![image](https://user-images.githubusercontent.com/42734840/148078630-c17aa09b-9595-4eff-bfe3-7771c4a5fffc.png)

2022-01-04 15:03 UTC, AdrienClairembault commented
This buttons isn't doing anything:

![image](https://user-images.githubusercontent.com/42734840/148078858-db9dea33-df1a-42d8-92bc-9c9b100174d9.png)

I suppose it should toggle some search criteria ?

2022-01-04 15:04 UTC, AdrienClairembault commented
Visual issues when adding a new language to my form:

![image](https://user-images.githubusercontent.com/42734840/148079124-c4a3265b-87ea-41e4-a908-13baf563dd0c.png)

2022-01-05 10:20 UTC, btry commented
> Visual issues when trying to add a category from the "New item - Form" page:

this page is not yet converted into Twig. 

> Adding a validator to my form doens't seem to work

Fixed 

> Visual issues when creating a section (entity name + child entity checkbox):

Even when isEntityAssign returns false, the UI shows them. I tried to design templates as generic as possible, by using core's templates. The elements related to the entity are disabled, but I agree it would be better ti not show them. To do thos, it may be better to fix the template in the core.

About the empty ribbon : I did not focused on that for now. I find it not disturbing as is. Defining the icon for this itemtype should solve the topic. This is also true for question itemtype.

2022-01-05 10:48 UTC, btry commented
> Adding an actor to a target doesn't seem to work:

fixed

2022-01-05 14:38 UTC, btry commented
![image](https://user-images.githubusercontent.com/14139801/148235249-ed1a0c79-d57b-4d26-b31f-9f439bd407f7.png)

The toggle button is always displayed by GLPI. i think this page should not show the search filters, then GLPI should provide some mechanism to disable this toggle button.

2022-01-05 14:49 UTC, btry commented
ribbon in form language tab : 

needs 

```scss
.card_header {
   position:relative
}
```

This would also fix the other identified cases, but needs to be evaluated before inclusion in GLPI core.

2022-01-06 13:27 UTC, AdrienClairembault commented
> Even when isEntityAssign returns false, the UI shows them. I tried to design templates as generic as possible, by using core's templates. The elements related to the entity are disabled, but I agree it would be better ti not show them. To do thos, it may be better to fix the template in the core.

Done -> https://github.com/glpi-project/glpi/pull/10275.

2022-01-13 15:53 UTC, AdrienClairembault requested changes
## UI Stuffs / Subjective

1\) Maybe we can add a few improvement to this page ?
![image](https://user-images.githubusercontent.com/42734840/149357111-bb144aa5-dcc4-4941-9237-c98715110b87.png)
![image](https://user-images.githubusercontent.com/42734840/149357165-1667bd83-1320-40f1-af6c-f62d27807899.png)

The input move when you switch between group and users, maybe a vertical layout would use the available space better (not very important).

2\) Maybe add some margin before displaying the first section:
![image](https://user-images.githubusercontent.com/42734840/149357787-2834589b-3e09-40c2-9209-8c6e06576ae8.png)
![image](https://user-images.githubusercontent.com/42734840/149357829-05017d13-95f7-4a51-bd2c-74a982b9c600.png)

Also the dark grey backgrounds seems a bit out of place in the new UI.
Maybe there is some tabler component we would use here but I'm not sure which.


## Bugs

1\) If I click on this dropdown, the modal close itself and my unsaved question is lost:
![image](https://user-images.githubusercontent.com/42734840/149359329-116c3dfb-a8b7-4b68-8cef-e8f19a688f3f.png)

Seems to behave differently depending on the question type.
Textarea closes the dropdown immediatly but some others don't.

2\) If I switch between all the possible values, new inputs keep popping up below the form:
![image](https://user-images.githubusercontent.com/42734840/149359852-fa92b931-0663-45ed-bd19-b0989774802e.png)

3\) If the section isn't saved yet there is never any input however:
![image](https://user-images.githubusercontent.com/42734840/149360009-e4d1ea85-7ff9-4736-b5c6-f6e213d3647a.png)

4\) Same as 2 but for the submit button conditions:
![image](https://user-images.githubusercontent.com/42734840/149360139-19ca9efa-aee5-4847-8549-6663e11ed5d9.png)

5\) Same as 3 but for a new question, can't add any condition:
![image](https://user-images.githubusercontent.com/42734840/149360277-6a9c8f5e-dbf2-45c7-a758-478b777f38f9.png)

6\) When creating a question, submit button doesn't close the modal.
Each time I press the button another question is added in the background.
Also can't close the modal.
![image](https://user-images.githubusercontent.com/42734840/149360666-2adff3fb-4738-421c-b6b0-be7afe3b9db6.png)

7\) Same as 2 but when editing a question:
![image](https://user-images.githubusercontent.com/42734840/149360915-05b9b36d-f23e-4c16-ada7-a6d1af18a45d.png)

8\) Not sure if caused by the twig changes but I can submit some partial values for targets (no question selected):
![image](https://user-images.githubusercontent.com/42734840/149361436-ff80786f-7c57-438f-b437-e79de5da40a4.png)

9\) Same as 2 but for target condition:
![image](https://user-images.githubusercontent.com/42734840/149361675-12f1a1f9-179a-4d1c-801c-11446862dafe.png)

10\) Can't add validator as a requester for a target change or problem:
![image](https://user-images.githubusercontent.com/42734840/149361963-6c93d271-065e-4de0-8a0f-b0af341367b9.png)
After submitting the value isn't added.
It does work for target ticket, I'm even able to add the user multiple time (is this ok ?):
![image](https://user-images.githubusercontent.com/42734840/149362172-58a51e9c-16ca-492c-a40d-71261dad4705.png)

11\) Actor questions aren't visible in the preview:
![image](https://user-images.githubusercontent.com/42734840/149362430-385635aa-88c9-411d-93b4-4c3fe4f908a0.png)
![image](https://user-images.githubusercontent.com/42734840/149362450-92bf2828-bee8-4a68-abc8-78b45bdbf369.png)

12\) Saving a question doesn't close the modal, can't close with the exit button either.

2022-01-14 15:56 UTC, AdrienClairembault commented
Another weird tab bug that I've been able to reproduce:
If you go to a form and:
- Go to "Targets" tab
- Go to "Access types" tabs
- Go back to "Targets" tab
- Add a new target
-> On submit, you are redirected to the "Access types" tab instead of staying on the "Targets" tab

2022-01-14 16:01 UTC, btry commented
I just noticed similar behaviours elsewhere. I'll fix all those things next week.

2022-01-18 20:26 UTC, btry commented on RoboFile.php
> +      $this->_exec('tools/extract_template.sh');
As Robo is being abandonned in GLPI project, I pick the locales extraction tool from GLPI, to find strings from twig templates

2022-01-18 20:27 UTC, btry commented on ajax/question_add.php
> +    http_response_code(500);
err 500 is more appropriate here

2022-01-18 20:29 UTC, btry commented on ajax/condition.php
> +echo $condition->getConditionHtml($parent);
Atempt to simplify conditions creation and display for all conditionnable items. As conditions may be added to non-existing items (creating items and conditions at the same time), we need to forge items to make things work properly.

In other cases, loading them from DB is fine.

The most important need is to be able to find the form on top of the items, which are themselve parent of the conditions to show.

2022-01-18 20:30 UTC, btry commented on ajax/question_add.php
> +echo json_encode($json, JSON_UNESCAPED_UNICODE);
usually, we shoud should prevent unicode chars escaping

2022-01-18 20:31 UTC, btry commented on install/mysql/plugin_formcreator_empty.sql
> +  `uuid`                           varchar(255) DEFAULT NULL,
better indentation

2022-01-18 20:32 UTC, btry commented on js/scripts.js
> -         plugin_formcreator.moveUpItems(group);
the method is disabled, calling it is useless

2022-01-18 20:32 UTC, btry commented on js/scripts.js
> +      var items = $(event.currentTarget).find('> .grid-stack-item');
style problem here

2022-01-18 20:33 UTC, btry commented on js/scripts.js
> +         that.resetTabs();
when qhestions are moved, reset other tabs of the form to force reload of preview when the admin wants to test the form

2022-01-18 20:34 UTC, btry commented on js/scripts.js
> +      var id = item.getAttribute('data-id');
switch to vanilla JS when possible

2022-01-18 20:34 UTC, btry commented on js/scripts.js
> +         event.target.gridstack.update(
vanilla JS when possible

2022-01-18 20:34 UTC, btry commented on js/scripts.js
> -      return;
method was disabled (never  used in any release), dropping it

2022-01-18 20:35 UTC, btry commented on js/scripts.js
> +      var form = document.querySelector('form[data-itemtype="PluginFormcreatorQuestion"]');
vanilla JS if possible

2022-01-18 20:36 UTC, btry commented on js/scripts.js
> +         contentType: false,
processData and contentType are here to help JQuery to work with FormData object; hels to remove useless JQuery use

2022-01-18 20:36 UTC, btry commented on js/scripts.js
> +         var sectionId = form.querySelector('select[name="plugin_formcreator_sections_id"]').value;
less JQuery

2022-01-18 20:36 UTC, btry commented on js/scripts.js
> +         dataType: 'json'
returned body switched to JSON

2022-01-18 20:36 UTC, btry commented on js/scripts.js
> +         question.find('[data-field="name"]').text(data['name'])
returned body switched to JSON

2022-01-18 20:36 UTC, btry commented on js/scripts.js
> +      var id = item.getAttribute('data-id');
less JQuery

2022-01-18 20:37 UTC, btry commented on js/scripts.js
> +         }
fix non closing modals.

2022-01-18 20:38 UTC, btry commented on js/scripts.js
> +         }
fix non closing modal

2022-01-18 20:38 UTC, btry commented on js/scripts.js
> +         dataType: 'json'
switch to json response

2022-01-18 20:39 UTC, btry commented on js/scripts.js
> +   this.addSection = function (event) {
event pssed to function, helping to mot search too much in the DOM

2022-01-18 20:39 UTC, btry commented on js/scripts.js
> +   this.editSection = function (event) {
event passed to function, here as well

2022-01-18 20:43 UTC, btry commented on js/scripts.js
> +   this.changeActor = function(type, value) {
factorization of :
plugin_formcreator_ChangeActorRequester
plugin_formcreator_ChangeActorWatcher
plugin_formcreator_ChangeActorASsigned

2022-01-18 20:44 UTC, btry commented on js/scripts.js
> -function plugin_formcreator_ChangeActorRequester(value) {
factorized

2022-01-18 20:44 UTC, btry commented on js/scripts.js
> -function plugin_formcreator_ChangeActorWatcher(value) {
factorized

2022-01-18 20:44 UTC, btry commented on js/scripts.js
> -function plugin_formcreator_ChangeActorAssigned(value) {
factorized

2022-01-18 20:45 UTC, btry commented on js/scripts.js
> +   this.deleteActor = function (item) {
convert add / delete of target actors calls into Ajax, for better UX.

2022-01-18 20:48 UTC, btry commented on js/scripts.js
> -}
no longer used

2022-01-18 20:49 UTC, btry commented on js/scripts.js
> +   target.closest('div.row').remove();
update to new DOM, drop jquery usage

2022-01-18 20:50 UTC, btry commented on tests/3-unit/PluginFormcreatorCondition.php
> +      $this->login('glpi', 'glpi');
the methid is not static

2022-01-18 20:50 UTC, btry commented on tests/3-unit/PluginFormcreatorCondition.php
> -      $output = $condition->getConditionsFromItem($question);
method is now static

2022-01-18 20:50 UTC, btry commented on tests/3-unit/PluginFormcreatorCondition.php
> -      $output = $condition->getConditionsFromItem($question);
method is now static

2022-01-18 20:50 UTC, btry commented on tests/3-unit/PluginFormcreatorCondition.php
> +      $this->login('glpi', 'glpi');
the methid is not static

2022-01-18 20:50 UTC, btry commented on tests/3-unit/PluginFormcreatorCondition.php
> +      $form = \PluginFormcreatorForm::getByItem($question);
use a more generic method to find a form from an item inside it

2022-01-18 20:51 UTC, btry commented on tests/3-unit/PluginFormcreatorCondition.php
> -      $question2->updateConditions([
adding conditions can be done while adding the question

2022-01-18 20:52 UTC, btry commented on inc/form.class.php
> -   public function getFromDBBySection(PluginFormcreatorSection $item) {
replaced by more generic getByItem method

2022-01-18 20:53 UTC, btry commented on inc/form.class.php
> -   public function getFromDBByQuestion(PluginFormcreatorQuestion $question) {
replaced by more generic getByItem method

2022-01-18 20:54 UTC, btry commented on inc/question.class.php
> +      // return true;
too much complex to convert now, lets keep this draft and continue in an other PR

2022-01-18 20:55 UTC, btry commented on inc/section.class.php
> +   }
forbid some massive actions

2022-01-18 20:56 UTC, btry commented on inc/target_actor.class.php
> +      $requiredKeys = ['itemtype', 'items_id', 'actor_role', 'actor_type'];
add integrity checks, does not handles all cases for now, but fix the inconsistency found this week

2022-01-18 20:57 UTC, btry commented on inc/targetproblem.class.php
> +   public function defineTabs($options = []) {
like target ticket and target change : swtch to a multiple tabs design to edit this target

2022-01-18 21:00 UTC, btry commented on inc/targetticket.class.php
> -   }
factorize with all targets types, see implementation in AbstractTarget. 

If adding actors by default is not wanted, then create for each class a method to add default actors.

2022-01-18 21:01 UTC, btry commented on inc/targetticket.class.php
>        PluginFormcreatorQuestion::dropdownForForm(
dropdownForForm now gets form object as 1st arg

2022-01-19 14:32 UTC, AdrienClairembault requested changes
1\) The visibility condition dropdown is too large, it doesn't seem to fit the input:
![image](https://user-images.githubusercontent.com/42734840/150139195-e658bcc7-c1e2-41cb-9ba9-0c8105c478ba.png)

Also, if you have a scroll-able page (a big question form like the checkbox question type for example), the options are disconnected from the input:

![image](https://user-images.githubusercontent.com/42734840/150139413-2828b899-aaa9-4e1a-9c0c-58392b2ce1f6.png)

2\) When creating a form, "All langages" is displayed differently when selected vs the value in the dropdown:
![image](https://user-images.githubusercontent.com/42734840/150139823-baa72483-95af-4c8d-bd3b-4f9b58fd15f5.png)
  
Also it should be  "All lang**u**ages" instead of  "All langages".

3\) I'm not sure what happened but the first form I tried to create didn't had the correct default values.
The visible option was on "No", the default language on "All Languages" and both colors to white #FFFFFF.
After submitting the form it was also not saved in the database instead it was used to modify an existing form:
![image](https://user-images.githubusercontent.com/42734840/150142433-415230ac-c021-40e2-87c6-3623f3c7e1dc.png)
I'm 100% sure of it as it was the exact colors and icons I had picked + the correct time.

Every other form I tried to create after this didn't have the issue so I wasn't able to reproduce this bug.

UPDATE, I've been able to reproduce it: 
- Save the questions on an existing form
- Try to create a new form

![image](https://user-images.githubusercontent.com/42734840/150143434-1f2f2f6d-1386-4d2d-b09e-d156ed129b66.png)

4\) The validation input still "moves around" depending on the selected value
![image](https://user-images.githubusercontent.com/42734840/150140483-114d36fc-355c-4e27-87bc-dfa3ad1f36b2.png)
It should use the new bootstrap col/row forms instead of the legacy html table.

The label "Need validaton?" has a spelling mistake.


5\) If I click twice on the "move section down" button (which I first though was a button to hide the section content, not move my section. not sure how to improve this UI wise) then some questions are not shown anymore.

Before:
![image](https://user-images.githubusercontent.com/42734840/150144105-d5ee8943-a6f7-4c5c-8a66-a4925c4bb02e.png)

After: 
![image](https://user-images.githubusercontent.com/42734840/150144162-514d910f-dbc5-40c7-bc14-d5cc346fabfa.png)


6\) The submit button visibility condition trigger an error:
![image](https://user-images.githubusercontent.com/42734840/150145175-4a46c502-1c37-4042-bc99-dbdaa31b43c4.png)

You need to set a condition and save, the error wont be shown if no conditions are set.

Seems to be OK for questions and sections.

7\) I can't update my target ticket, right errors.
![image](https://user-images.githubusercontent.com/42734840/150145942-cbc8b4eb-fa76-4a4f-9eec-276b3887887d.png)

This is a GLPI with only formcreator and no rights / configuration modification.

 8\) Two issues with the actor fields:
![image](https://user-images.githubusercontent.com/42734840/150146308-1e1bf612-d9e0-4e52-ad06-365436be9156.png)

There is an excessive margin compared to similar inputs used by GLPI:
![image](https://user-images.githubusercontent.com/42734840/150146570-ac581618-3221-446a-9528-b1e73d6eadf9.png)

Also the default "----" option shouldn't be selectable (might be fixed by https://github.com/glpi-project/glpi/pull/10288)

9\) I can't click on these icons in a form target, seems to do nothing:
![image](https://user-images.githubusercontent.com/42734840/150147096-e0fc7aed-4818-4f31-a505-00446d43f7aa.png)

Beside not having a "pointer" cursor, the 'delete' button seems to trigger a 404 error:
![image](https://user-images.githubusercontent.com/42734840/150147200-4df4a361-352d-43fe-8fab-93e1c7dd2dda.png)
The "notification" button doesn't seem to do anything.

Same 404 error if I try to add another actor.

10\) The "issues" button lead me to an error:

![image](https://user-images.githubusercontent.com/42734840/150147683-f2eeb587-3b90-4455-95bf-840b139c296f.png)
![image](https://user-images.githubusercontent.com/42734840/150147651-e551ccca-415c-4511-8828-c6964b824f90.png)

The issue seems to be that I'm able to add a "Tag" question to my forms without having the tag plugin installed or activated.
This also prevent me from displaying this form.

I think firstly I shouldn't be able to add a Tag question if I don't have the plugin activated.
Even tho, this kind of case might still happen (If I enable tag, create a tag question then disable the tag plugin for example) so we should avoid throwing an error and just skip the question.

11\) No breadcrumbs when searching or displaying form answers:
![image](https://user-images.githubusercontent.com/42734840/150148116-a1179328-7d9b-430b-aceb-44bc67986b61.png)


12\) Error on target change:
![image](https://user-images.githubusercontent.com/42734840/150149054-5fff2b9c-bc6f-4531-85b6-1fb3899809ff.png)

13\) I have a test form with 6 targets, when I submit it 0 of them are created.

Here is the form export (had to save it as .json.txt as json file are forbidden it seems).

[export_formcreator_20220119_1521.json.txt](https://github.com/pluginsGLPI/formcreator/files/7897870/export_formcreator_20220119_1521.json.txt)

14\) I have this warning in my logs:
```
[2022-01-19 15:01:53] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: is_captcha_enabled in /home/adrie/localhost/gmaster2/plugins/formcreator/front/form_profile.form.php at line 48  
```

2022-01-27 09:16 UTC, btry commented
> 1) The visibility condition dropdown is too large, it doesn't seem to fit the input:

Reduced; but the width is not consistent everywhere. There is a problem with design of questions. This form is not converted into Twig and I integrated the twig version of conditions rendering in the old code. 

A full technical redesign of this part is needed because of several reasons (incoming devs, a communautary problem report, migration to twig, constant addition of options making this part had to maintain, bug prone). 

I want to fix that in a distinct PR to have a chance to submit a readable and understandable code design. This PR is too big and spreads on to many topics (fixes unrelated ti twig conversion) now.

> Also, if you have a scroll-able page (a big question form like the checkbox question type for example), the options are disconnected from the input:

should  be fixed with a speecific PR, see above comment

> 2) When creating a form, "All langages" is displayed differently when selected vs the value in the dropdown

fixed in GLPI, was a RTL problem. Typo fixed.

> 3) I'm not sure what happened but the first form I tried to create didn't had the correct default values.

fixed. Was a problem of data stored in session, not erased when a updating form properties, not changing the form object itself. see PluginFormcreatorForm::post_updateItem:() 

Maybe a better solution should be found as it is currently hacky.


> 4) The validation input still "moves around" depending on the selected value

out of topic of this PR : this tab is not converted into Twig yet. Also not very harmful, other things have priority

2022-01-27 10:26 UTC, AdrienClairembault approved these changes
OK for now, it's hard to keep track of everything with so many comments, commits and changes.
I'll test everything again later (next beta release maybe ?)

2022-01-27 10:48 UTC, btry commented
I'm still fixing last issues; i'll update the previous comment. I('ll tell you when tie PR is ready for a new review

2022-01-31 08:09 UTC, merged