Add hook to allow plugins to define new menus
pluginsGLPI/formcreator pull request #2624
Opened 2022-03-02 15:08 UTC by AdrienClairembault

### Changes description

* Add a new `formcreator_add_menu` hook to allow plugins to add their own specific menus to formcreator interface.
* Convert existing fa-icons to ti-icons to match changes done in GLPI core.

Example usage of the new hook:
```php
$PLUGIN_HOOKS['formcreator_add_menu']['demo'] = [
   'waiting_workflow' => [
      'default' => PluginFormcreatorIssue::getSearchURL(false),
      'title'   => __('Pending forms', 'formcreator'),
      'icon'    => 'fa-fw ti ti-forms',
      'after'   => 'my_assistance_requests'
   ],
];
```

![image](https://user-images.githubusercontent.com/42734840/156388507-8ad3cd25-7595-4e91-99c0-3b07e01e1d81.png)

2022-03-10 12:23 UTC, btry requested changes

2022-03-10 12:23 UTC, btry commented on tests/code-coverage/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
this file should not be in the repo

2022-03-11 14:11 UTC, AdrienClairembault commented
Is this the one were you told me that this hook isn't needed since we can already redefine menus with a core hook ?

I was worried of what would happen if the plugins redefining the menus were loaded before formcreator.
It would maybe be best to have some kind of code in the plugins that force them to be loaded after formcreator (thus no need for this menu hook).

I'll remove the menu part and keep the new icons if that's ok with you, since most GLPI menus have been migrated to them.

2022-03-14 09:32 UTC, btry submitted a review, later dismissed

2022-03-15 15:16 UTC, AdrienClairembault commented
Rebase + force-pushing to check if tests are ok  now

2022-03-17 10:00 UTC, btry approved these changes

2022-03-17 10:02 UTC, merged