fix: adjust dashboard widget height
pluginsGLPI/formcreator pull request #3490
Opened 2024-04-09 13:27 UTC by ccailly

### Changes description

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #N/A

Correct dashboard widget height in `install.php`.
Previous pull request, #3306 refactored UI of widgets but missed updating install.php.
A subsequent commit updated `install.php` but set widget height to 1 instead of the correct value 2.

This PR fixes the widget height value to 2.

2024-04-09 14:05 UTC, Rom1-B requested changes

2024-04-09 14:05 UTC, Rom1-B commented on install/upgrade_to_2.13.10.php
> +<?php
It seems simpler and less risky not to resize at all at the update, neither in this version nor in 2.13.7.

2024-04-10 06:53 UTC, btry requested changes
To upgrade to version 2.13.0 the version constant in setup.php must be up to date. Also in install.php there is a matrix which modelizes versions sequence It needs a new entry 2.13.9 => 2.13.10.

Also, I don't expect to release a new version as the plugin reached it end of life and we are implementing forms in GLPI core (v11).

2024-04-12 12:45 UTC, Rom1-B approved these changes

2024-04-12 12:45 UTC, ccailly commented
As discussed with @Rom1-B above and IRL, it's probably wiser not to change the widget size during an update.
It's possible that some users may have manually modified their widgets, so only new installations of the plugin will benefit from the new widget size.

2024-04-12 13:18 UTC, btry commented
Hi 

> As discussed with @Rom1-B above and IRL, it's probably wiser not to change the widget size during an update.
It's possible that some users may have manually modified their widgets, so only new installations of the plugin will benefit from the new widget size.

Actually, the plugin takes measures to prevent users to modify its mini dashboard. Noone should be able to modify it (neither super-admins). This is why it should be safe to modify it programmatically

2024-04-22 07:24 UTC, AdrienClairembault requested changes
Agreed with @btry.

The `resizeWidgets` function must not be deleted.

2024-04-22 13:17 UTC, AdrienClairembault approved these changes

2024-04-22 13:22 UTC, btry approved these changes

2024-08-30 11:55 UTC, merged